[build]
target = "riscv64gc-unknown-none-elf"
rustflags = [
    # Linker script
    "-Clink-arg=-Tlds/virt.lds",
    # Target features
    "-Ctarget-feature=+m,+a,+f,+d,+c,+zba,+zbb,+zbc,+zbs",
]

[target.riscv64gc-unknown-none-elf]
# Name of the bare-metal RISC-V C compiler
linker = "riscv64-elf-gcc"
