[package]
name = "example-hello-world"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]
test = false
bench = false

[profile.dev]
opt-level = 0
lto = "off"

[profile.release]
codegen-units = 1
opt-level = 3
lto = "fat"

[dependencies]
