[build]
target = "riscv64gc-unknown-none-elf"

[target.riscv64gc-unknown-none-elf]
rustflags = [
    # Linker Script
    "-Clink-arg=--script=./src/lds/virt.lds",
    # Target Features
    "-Ctarget-feature=+v,+zba,+zbb,+zbs",
]
